"""London Crime Pulse Explorer — Streamlit app."""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pydeck as pdk
import streamlit as st

from src.cleaning.clean_crime_data import (
    HAS_VALID_COORDINATES_COLUMN,
    IS_WITHIN_LONDON_BBOX_COLUMN,
    LATITUDE_COLUMN,
    LONGITUDE_COLUMN,
)
from src.config import (
    DEFAULT_TESTING_MONTH,
    LONDON_BBOX,
    OUTPUTS_REPORTS_DIR,
    PROCESSED_DATA_DIR,
)
from src.validation.validate_crime_data import (
    LSOA_CODE_COLUMN,
    LSOA_NAME_COLUMN,
    REPORT_FILENAME_TEMPLATE,
    TOP_LSOA_COUNT,
    processed_parquet_path,
)

MONTH = DEFAULT_TESTING_MONTH
CRIME_TYPE_COLUMN = "crime_type"
REPORTED_BY_COLUMN = "reported_by"
MONTH_COLUMN = "month"
MONTH_LABEL_COLUMN = "month_label"
LOCATION_COLUMN = "location"
FALLS_WITHIN_COLUMN = "falls_within"
LAST_OUTCOME_CATEGORY_COLUMN = "last_outcome_category"
PREVIEW_ROW_COUNT = 200

MAP_POINT_LIMITS: dict[str, int | None] = {
    "5,000": 5_000,
    "25,000": 25_000,
    "All": None,
}
MAP_TOOLTIP_COLUMNS = [
    MONTH_COLUMN,
    CRIME_TYPE_COLUMN,
    LOCATION_COLUMN,
    LSOA_NAME_COLUMN,
    LSOA_CODE_COLUMN,
    REPORTED_BY_COLUMN,
    FALLS_WITHIN_COLUMN,
    LAST_OUTCOME_CATEGORY_COLUMN,
]
ALL_CRIME_TYPES_LABEL = "All"


@st.cache_data
def load_dataset(month: str, parquet_path: str) -> pd.DataFrame:
    """Load cleaned crime data from processed Parquet.

    ``parquet_path`` is part of the cache key so Streamlit reloads when the
    file is regenerated by the pipeline.
    """
    return pd.read_parquet(Path(parquet_path))


def sorted_unique_values(series: pd.Series) -> list[str]:
    """Return sorted unique non-null string values for display."""
    return sorted(series.dropna().astype("string").unique().tolist())


def filter_by_crime_type(df: pd.DataFrame, crime_type: str) -> pd.DataFrame:
    """Return rows for one crime type, or the full dataframe for ``All``."""
    if crime_type == ALL_CRIME_TYPES_LABEL:
        return df
    return df.loc[df[CRIME_TYPE_COLUMN].astype("string") == crime_type].copy()


def quality_report_path(month: str) -> Path:
    return OUTPUTS_REPORTS_DIR / REPORT_FILENAME_TEMPLATE.format(month=month)


@st.cache_data
def load_quality_report(month: str, report_path: str) -> str | None:
    """Load the pipeline data quality report text, if it exists."""
    path = Path(report_path)
    if not path.is_file():
        return None
    return path.read_text(encoding="utf-8")


def value_counts_frame(df: pd.DataFrame, column: str) -> pd.DataFrame:
    """Return a single-column dataframe of value counts for bar charts."""
    counts = df[column].value_counts(dropna=False).sort_values(ascending=False)
    counts.index = counts.index.map(lambda value: str(value) if pd.notna(value) else "(missing)")
    return counts.rename("count").to_frame()


def top_lsoa_counts_frame(df: pd.DataFrame, limit: int = TOP_LSOA_COUNT) -> pd.DataFrame:
    """Return top LSOAs by crime count, aligned with the pipeline report."""
    lsoa_df = df.dropna(subset=[LSOA_CODE_COLUMN])
    if lsoa_df.empty:
        return pd.DataFrame(columns=["count"])

    top_lsoas = (
        lsoa_df.groupby([LSOA_CODE_COLUMN, LSOA_NAME_COLUMN], dropna=False)
        .size()
        .sort_values(ascending=False)
        .head(limit)
    )
    labels = [
        f"{lsoa_code} | {lsoa_name if pd.notna(lsoa_name) else '(no name)'}"
        for lsoa_code, lsoa_name in top_lsoas.index
    ]
    return pd.DataFrame({"count": top_lsoas.values}, index=labels)


def filter_map_points(df: pd.DataFrame) -> pd.DataFrame:
    """Keep only rows that are safe to plot on the London point map."""
    mask = df[HAS_VALID_COORDINATES_COLUMN] & df[IS_WITHIN_LONDON_BBOX_COLUMN]
    return df.loc[mask].copy()


def limit_map_points(df: pd.DataFrame, max_points: int | None) -> pd.DataFrame:
    """Cap the number of points sent to the map for performance."""
    if max_points is None or len(df) <= max_points:
        return df
    return df.sample(n=max_points, random_state=42)


def prepare_map_tooltip_data(df: pd.DataFrame) -> pd.DataFrame:
    """Return map rows with string tooltip fields and explicit lat/lon columns."""
    map_df = df[MAP_TOOLTIP_COLUMNS + [LONGITUDE_COLUMN, LATITUDE_COLUMN]].copy()
    for column in MAP_TOOLTIP_COLUMNS:
        map_df[column] = map_df[column].astype("string").fillna("")
    return map_df


def build_crime_point_map(map_df: pd.DataFrame) -> pdk.Deck | None:
    """Build a PyDeck scatter map centred on London."""
    if map_df.empty:
        return None

    center_latitude = (LONDON_BBOX["latitude_min"] + LONDON_BBOX["latitude_max"]) / 2
    center_longitude = (LONDON_BBOX["longitude_min"] + LONDON_BBOX["longitude_max"]) / 2

    layer = pdk.Layer(
        "ScatterplotLayer",
        data=map_df,
        get_position=[LONGITUDE_COLUMN, LATITUDE_COLUMN],
        get_fill_color=[220, 50, 70, 140],
        get_radius=25,
        radius_min_pixels=2,
        radius_max_pixels=8,
        pickable=True,
    )

    view_state = pdk.ViewState(
        latitude=center_latitude,
        longitude=center_longitude,
        zoom=9,
        pitch=0,
    )

    tooltip = {
        "html": (
            "<b>{crime_type}</b><br/>"
            "Month: {month}<br/>"
            "Location: {location}<br/>"
            "LSOA: {lsoa_name} ({lsoa_code})<br/>"
            "Reported by: {reported_by}<br/>"
            "Falls within: {falls_within}<br/>"
            "Outcome: {last_outcome_category}"
        ),
        "style": {
            "backgroundColor": "#1e1e1e",
            "color": "white",
        },
    }

    return pdk.Deck(
        layers=[layer],
        initial_view_state=view_state,
        tooltip=tooltip,
        map_style="road",
    )


st.set_page_config(
    page_title="London Crime Pulse Explorer",
    page_icon="🗺️",
    layout="wide",
)

st.title("London Crime Pulse Explorer")
st.caption("3D hexbin map of London street-level crime — work in progress")

dataset_path = processed_parquet_path(MONTH, PROCESSED_DATA_DIR)

st.subheader("Dataset status")

if not dataset_path.is_file():
    st.error(
        f"Processed dataset not found for **{MONTH}**.\n\n"
        f"Expected file: `{dataset_path}`\n\n"
        "Run `python run_pipeline.py` to generate the cleaned Parquet file."
    )
    st.stop()

df = load_dataset(MONTH, str(dataset_path))

month_values = sorted_unique_values(df[MONTH_COLUMN])
month_labels = (
    sorted_unique_values(df[MONTH_LABEL_COLUMN])
    if MONTH_LABEL_COLUMN in df.columns
    else month_values
)
crime_types = sorted_unique_values(df[CRIME_TYPE_COLUMN])
police_forces = sorted_unique_values(df[REPORTED_BY_COLUMN])

with st.sidebar:
    st.header("Filters")
    selected_crime_type = st.selectbox(
        "Crime type",
        options=[ALL_CRIME_TYPES_LABEL, *crime_types],
    )
    point_limit_label = st.select_slider(
        "Max points on map",
        options=list(MAP_POINT_LIMITS.keys()),
        value="5,000",
    )

filtered_df = filter_by_crime_type(df, selected_crime_type)
max_points = MAP_POINT_LIMITS[point_limit_label]

status_col, rows_col, month_col, types_col, forces_col = st.columns(5)
status_col.metric("Status", "Loaded")
rows_col.metric("Total rows", f"{len(df):,}")
month_col.metric("Month values", len(month_values))
types_col.metric("Crime types", len(crime_types))
forces_col.metric("Police forces", len(police_forces))

st.caption(f"Source: `{dataset_path}`")

if selected_crime_type != ALL_CRIME_TYPES_LABEL:
    st.info(
        f"Filter active: **{selected_crime_type}** — "
        f"{len(filtered_df):,} of {len(df):,} rows."
    )

detail_col, forces_col_detail = st.columns(2)

with detail_col:
    st.markdown("**Available month value**")
    if month_labels:
        st.write(", ".join(month_labels))
    else:
        st.write("—")

    st.markdown("**Available crime types**")
    if crime_types:
        st.write(", ".join(crime_types))
    else:
        st.write("—")

with forces_col_detail:
    st.markdown("**Available police forces**")
    if police_forces:
        st.write(", ".join(police_forces))
    else:
        st.write("—")

report_path = quality_report_path(MONTH)
report_text = load_quality_report(MONTH, str(report_path))

st.subheader("Data quality report")
if report_text is None:
    st.warning(
        f"Data quality report not found for **{MONTH}**.\n\n"
        f"Expected file: `{report_path}`\n\n"
        "Run `python run_pipeline.py` to generate the report."
    )
else:
    with st.expander("View pipeline data quality report", expanded=False):
        st.text(report_text)
    st.caption(f"Source: `{report_path}`")

st.subheader("Summary charts")

if filtered_df.empty:
    st.warning("No rows match the selected crime type filter.")
else:
    chart_left, chart_right = st.columns(2)

    with chart_left:
        st.markdown("**Crimes by crime type**")
        st.bar_chart(value_counts_frame(filtered_df, CRIME_TYPE_COLUMN), width="stretch")

    with chart_right:
        st.markdown("**Crimes by police force**")
        st.bar_chart(value_counts_frame(filtered_df, REPORTED_BY_COLUMN), width="stretch")

    st.markdown(f"**Top {TOP_LSOA_COUNT} LSOAs by crime count**")
    st.bar_chart(top_lsoa_counts_frame(filtered_df), width="stretch")

st.subheader("Crime point map")

if filtered_df.empty:
    st.warning("No map-ready view is available because the filter returned no rows.")
else:
    map_points_df = filter_map_points(filtered_df)
    display_map_df = prepare_map_tooltip_data(
        limit_map_points(map_points_df, max_points)
    )

    filter_note = (
        f" for **{selected_crime_type}**"
        if selected_crime_type != ALL_CRIME_TYPES_LABEL
        else ""
    )
    st.caption(
        f"Showing {len(display_map_df):,} of {len(map_points_df):,} map-ready points"
        f"{filter_note} (`{HAS_VALID_COORDINATES_COLUMN}` and "
        f"`{IS_WITHIN_LONDON_BBOX_COLUMN}`)."
    )

    point_map = build_crime_point_map(display_map_df)
    if point_map is None:
        st.info("No map-ready crime points to display for the current filter.")
    else:
        st.pydeck_chart(point_map, width="stretch")

st.subheader("Cleaned data preview")
if filtered_df.empty:
    st.warning("No rows to preview for the current filter.")
else:
    st.dataframe(filtered_df.head(PREVIEW_ROW_COUNT), width="stretch")
    st.caption(
        f"Showing first {min(PREVIEW_ROW_COUNT, len(filtered_df)):,} of "
        f"{len(filtered_df):,} filtered rows."
    )
